#!/bin/bash -i
set +o history
cur_dir=$PWD
if [ "$1" == '-h' -o "$1" == '--help' ]; then
   args="$1"
   echo "rpyTranslations (populate|fix-empty|check|diff|reorder|--help) [args] [options]"
   shift
fi
while test $# -gt 0; do
   if [ "$1" == '-o' -o "$1" == '--subdir' ]; then
      args="$args '$1' '`echo "$2" |sed "s/'/'\''/g"`'"
      shift
   elif test -f "$1"; then args="$args '`realpath "$1" |sed "s/'/'\''/g"`'"
   else args="$args '`echo "$1" |sed "s/'/'\''/g"`'"
   fi
   shift
done
cd "<path_to_rpyTranslations_dir>"#ex: $HOME/Documents/Python3
/bin/sh -c -- "python3 -m rpyTranslations $args"
cd "$cur_dir"
